### ISSUE TITLE
Add support for LR30 Hybrid+

### ISSUE THREAD

**Issue by chris-schra** [CodeFoodPixels/robovac#27]
Thanks for the fork!
I tried to add my LR30 Hybrid+ but received a log error that model T2181 is not supported.
I was keen enough to add it to robovac.py (as X series model) and it seems to work. I'd create a PR but it seems I'm unable to find the correct upstream... sorry :/

**Comment by Nicko33127** [comment]
> Thanks for the fork! I tried to add my LR30 Hybrid+ but received a log error that model T2181 is not supported. I was keen enough to add it to robovac.py (as X series model) and it seems to work. I'd create a PR but it seems I'm unable to find the correct upstream... sorry :/

Hiya, I'm 2 days old new with GitHub and HA but was working on adding my LR30+ yesterdays and managed to get it work. 
Some details on the below link but in short use the beta 4 of this fork and disable auto search IP and type the IP manually.

Now because I'm new with HA I still dunno how to add the scrips for the specific cards. Bit the mushroom card work just fine to start pause, go empty bin ect.

I would like to be able to control the room I want to clean but not here yet.

https://github.com/CodeFoodPixels/robovac/issues/24

**Comment by CodeFoodPixels** [comment]
LR30 should be supported in the beta versions

**Comment by CodeFoodPixels** [comment]
This should be in v1.1.0
